### ISSUE TITLE
use with BRD & GreenAddress

### ISSUE THREAD

**Issue by tmornini** [dan-da/hd-wallet-derive#19]
Hey there.

I'm writing about using [url=https://github.com/dan-da/hd-wallet-dervice]https://github.com/dan-da/hd-wallet-derive[/url] with a couple of popular wallets.

I could really use this tool to help with my tax preparation this year, particularly in combination with your sister tool: [url=https://github.com/dan-da/hd-wallet-addrs]https://github.com/dan-da/hd-wallet-addrs[/url]

I've spent some time banging my head on the wall trying to work up from seed word lists from BRD (formerly Bread Wallet) and GreenAddress (old Blockstream version, not brand new version).

Does you happen to know how to use these tools with those wallets' seed word lists?

Thanks!

**Comment by dan-da** [comment]
Hey, I'd be glad to assist.  

We just need to know what HD path to start deriving from for each wallet software.  I'll look around for any docs on that.

I don't have either of those wallets installed to test with, so it would be helpful if you could create a new (empty) wallet for testing in each (BRD and Greenwallet), and paste here the mnemonic and the first 3 generated addresses for each.   That way I can verify that the addresses generated by hd-wallet-derive match those of the wallet software. 

Also, please include the software version number of each, at the time of wallet creation.

**Comment by dan-da** [comment]
For breadwallet, I found:

> it uses a derivation path of m/0'/0 for receive addresses and m/0'/1 for change addresses
source: https://bitcointalk.org/index.php?topic=2062242.0

This means one would pass --path="m/0'/0" to hd-wallet-derive or --path-"m/0'" to hd-wallet-addrs.

I didn't see discussion about Greenwallet's path yet.

**Comment by dan-da** [comment]
Hmm, it seems that GreenAddress does not (did not) follow the Bip32 scheme due to the way they use multisig.  

source: https://www.reddit.com/r/greenaddress/comments/6wy90b/bip_44/dmbna1w?utm_source=share&utm_medium=web2x

It sounds that GreenAddress will not work with the tools I've written.  So your best bet would be to check if the software has an "export all addresses" functionality, or if someone else has written a tool to export them from a master key.

Update:  I found the following:

> Hi,
> 
> It's not possible unless you basically construct a multisig between your key and GreenAddress' and call our public apis (api.greenaddress.it for the documentation), like our open source wallets on github/stores do basically.
> 
> We also have 2of3 and a tool for manual recovery of both 2of2 and 2of3 at https://github.com/greenaddress/garecovery and example code at https://github.com/greenaddress/gaexamples
> 
> hope it helps!

source: https://www.reddit.com/r/greenaddress/comments/7l9qph/importing_greenaddress_seed_into_other_wallets/drkmbl0?utm_source=share&utm_medium=web2x

and also:

> As GreenAddress is a multi-sig wallet, your private keys (the top level seed derived from you mnemonics, and subsequent addresses derived from it using BIP32) can only sign one side of any transaction to move coins from your wallet. As explained in our FAQ at https://greenaddress.it/faq, you need GreenAddress to sign the other side (after verifying 2FA if enabled). So your private key is not any use to you on its own.
> 
> The exception is for recovery (nlocktime) transactions, which are pre-signed by the service. Our recovery tool gentle contains code to derive your keys and send these transactions once the nlocktime expires. We will shortly be releasing a much simpler tool in python with code that should be much easier to understand, in the event that you wish to understand how your mnemonic is derived.
> 
> If you wish to move your coins to a BIP44 style wallet that you alone control then you will need to send your coins to a newly generated address.

source: https://www.reddit.com/r/greenaddress/comments/6gxyue/get_private_key_from_mnemonic/diu723j?utm_source=share&utm_medium=web2x
